members:
  admin:
    - galargh
    - laurentsenta
repositories:
  github-action-releaser:
    allow_auto_merge: false
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_squash_merge: true
    archived: false
    auto_init: false
    delete_branch_on_merge: false
    description: Release steps for github actions.
    has_downloads: true
    has_issues: true
    has_projects: true
    has_wiki: true
    homepage_url: ""
    is_template: false
    topics: []
    visibility: public
    vulnerability_alerts: false
  github-mgmt:
    allow_auto_merge: false
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_squash_merge: true
    archived: false
    auto_init: false
    delete_branch_on_merge: true
    description: ""
    has_downloads: true
    has_issues: true
    has_projects: false
    has_wiki: false
    homepage_url: ""
    is_template: false
    template:
      owner: protocol
      repository: github-mgmt-template
    topics: []
    visibility: public
    vulnerability_alerts: false
    branch_protection:
      master:
        allows_deletions: false
        allows_force_pushes: false
        enforce_admins: false
        push_restrictions: []
        require_conversation_resolution: false
        require_signed_commits: false
        required_linear_history: false
        required_pull_request_reviews:
          dismiss_stale_reviews: false
          dismissal_restrictions: []
          pull_request_bypassers: []
          require_code_owner_reviews: false
          required_approving_review_count: 1
          restrict_dismissals: false
        required_status_checks:
          contexts:
            - Plan
          strict: true
    teams:
      triage:
        - ipdx
    files:
      README.md:
        branch: master
        commit_author: galargh
        commit_email: piotr.galar@gmail.com
        commit_message: Update README
        content: README.md
        overwrite_on_create: false
  ipdx:
    allow_auto_merge: false
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_squash_merge: true
    archived: false
    auto_init: false
    delete_branch_on_merge: false
    description: ""
    has_downloads: true
    has_issues: true
    has_projects: true
    has_wiki: true
    homepage_url: ""
    is_template: false
    topics: []
    visibility: public
    vulnerability_alerts: false
  projects-migration:
    allow_auto_merge: false
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_squash_merge: true
    archived: false
    auto_init: false
    delete_branch_on_merge: false
    description: ""
    has_downloads: true
    has_issues: true
    has_projects: true
    has_wiki: true
    homepage_url: ""
    is_template: false
    pages:
      cname: ""
      source:
        branch: main
        path: /docs
    topics:
      - github
      - graphql
    visibility: public
    vulnerability_alerts: false
    collaborators:
      admin:
        - galargh
  projects-status-history:
    allow_auto_merge: false
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_squash_merge: true
    archived: false
    auto_init: false
    delete_branch_on_merge: false
    description: ""
    has_downloads: true
    has_issues: true
    has_projects: true
    has_wiki: true
    homepage_url: ""
    is_template: false
    topics: []
    visibility: public
    vulnerability_alerts: false
    collaborators:
      admin:
        - galargh
  rust-sccache-action:
    allow_auto_merge: false
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_squash_merge: true
    archived: false
    auto_init: false
    delete_branch_on_merge: false
    description: ""
    has_downloads: true
    has_issues: true
    has_projects: true
    has_wiki: true
    homepage_url: ""
    is_template: false
    topics: []
    visibility: public
    vulnerability_alerts: true
    collaborators:
      admin:
        - galargh
  tf-aws-gh-runner:
    allow_auto_merge: false
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_squash_merge: true
    archived: false
    auto_init: false
    delete_branch_on_merge: false
    description: ""
    has_downloads: true
    has_issues: true
    has_projects: true
    has_wiki: true
    homepage_url: ""
    is_template: false
    topics: []
    visibility: public
    vulnerability_alerts: false
    teams:
      maintain:
        - ipdx
teams:
  ipdx:
    description: ""
    privacy: closed
    members:
      maintainer:
        - galargh
        - laurentsenta
