name: Update

on:
  workflow_run:
    workflows:
      - "Apply"
    types:
      - completed
  workflow_dispatch:

jobs:
  update:
    permissions:
      pull-requests: write
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Update PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while read number; do
            if [[ ! -z "$number" ]]; then
              if gh api -X PUT "/repos/${{ github.repository }}/pulls/$number/update-branch" >/dev/null 2>&1; then
                echo "${{github.repository}}#$number ✅"
              else
                echo "${{github.repository}}#$number ❌"
                echo "::warning title=update-branch failure::${{github.repository}}#$number"
              fi
            fi
          done <<< "$(gh api '/repos/${{ github.repository }}/pulls' --jq '.[] | .number')"
