name: Update

on:
  workflow_dispatch:

jobs:
  update:
    uses: protocol/github-mgmt-template/.github/workflows/update_reusable.yml@master
    secrets:
      GITHUB_APP_ID: ${{ secrets.RW_GITHUB_APP_ID }}
      GITHUB_APP_INSTALLATION_ID: ${{ secrets[format('RW_GITHUB_APP_INSTALLATION_ID_{0}', github.repository_owner)] }}
      GITHUB_APP_PEM_FILE: ${{ secrets.RW_GITHUB_APP_PEM_FILE }}
